version: '3.9'

services:
  php-test:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USERID: 1001
    volumes:
      - web:/var/www/html
    networks:
      - default-test
    expose:
      - "9000"
    environment:
      APP_ENV: 'test'
      APP_SECRET: '0f4e9fce56a0fac70f6391e974def300'
      DATABASE_URL: 'mysql://root:toor@db-test:3306/authapi_test?serverVersion=8&charset=utf8mb4'
#      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      JWT_PASSPHRASE: '07efb81710088b3834ad4ff0f0668bf6'

  nginx-test:
    image: nginx:1.23.2
    expose:
      - "80"
    volumes:
      - web:/var/www/html
      - ./docker/nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default-test
    depends_on:
      - php-test

  node-test:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        USERID: 1001
    volumes:
      - frontend:/var/www
    ports:
       - "4200:4200"
    networks:
      - default-test

  db-test:
    image: mariadb:10.9.4
    ports:
      - 3307:3306
    volumes:
      - db-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: authapi_test
      MYSQL_PASSWORD: authapi_test
      MYSQL_DATABASE: authapi_test
    networks:
      - default-test

networks:
  default-test:
    driver: bridge

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: $PWD/app/api
      o: bind
  frontend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/app/frontend
      o: bind

  db-test:
