version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USERID: 1001
    volumes:
      - web:/var/www/html
    networks:
      - default
    expose:
      - 9000
    depends_on:
      - db

  nginx:
    image: nginx:1.23.2
    ports:
      - 80:80
    volumes:
      - web:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
    depends_on:
      - php

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        USERID: 1001
    volumes:
      - frontend:/var/www
    ports:
      - 4200:4200
    networks:
      - default

  db:
    image: mariadb:10.9.4
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: authapi
      MYSQL_PASSWORD: authapi
      MYSQL_DATABASE: authapi
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: $PWD/app/api
      o: bind
  frontend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/app/frontend
      o: bind

  db: