#controllers:
#    resource: ../src/Controller/
#    type: attribute

authenticated_user:
    path: /api/authenticated_user
    methods: POST
    defaults:
        _controller: App\Controller\AuthenticatedUserController::getUserByToken
        _api_resource_class: App\Entity\User
        _api_item_operation_name: post_publication

security_role:
    path: /security/roles
    methods: GET
    defaults:
        _controller: App\Controller\SecureRoleController::getSecureRoles

authentication_token:
    path: /authentication_token
    methods: ['POST']
