name: pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: docker-compose up -d

      - name: Sleep for 1 minute
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Lint backend
        uses: actions/checkout@v2
        run: docker-compose exec php composer -d /var/www/html/api run lint

      - name: Lint frontend
        uses: actions/checkout@v2
        run: docker-compose exec node npm run lint