name: pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker
      - run: | 
          docker-compose up 
          docker-compose exec php composer -d /var/www/html/api run lint 
          docker-compose exec node npm run lint