name: pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install make
        run: sudo apt install -y make

      - name: Build docker
        run: make up

      - name: Install backend packages
        run: make install

      - name: Sleep for 15s
        run: sleep 15

      - name: Lint backend
        run: make lint-backend

      - name: Lint frontend
        run: make lint-frontend