name: pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker
        run: docker-compose up -d

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Lint backend
        run: docker exec api-with-frontend-php-1 composer

      - name: Lint frontend
        run: docker-compose exec node npm run lint