name: pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker
        run: docker-compose up -d

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Lint backend
        run: docker-compose exec -T php composer -d /var/www/html/api run lint

      - name: Lint frontend
        run: docker-compose exec -T node npm run lint