name: pull request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker
        run: docker-compose up -d

      - name: Sleep for 5 minute
        uses: jakejarvis/wait-action@master
        with:
          time: '5m'

      - name: Lint backend
        run: docker-compose exec php composer -d /var/www/html/api run lint

      - name: Lint frontend
        run: docker-compose exec node npm run lint